### ISSUE TITLE
knative serving operator screenshot is incorrect

### ISSUE THREAD

**Issue by mmurphy** [openshift-knative/docs#18]
**Describe the Bug**
the file
[knative-serving-operator-screen.png](https://github.com/openshift-knative/docs/blob/f055c805488c9a02bacc56e6a3e5520ede4bf495/modules/ROOT/assets/images/knative-serving-operator-screen.png) is a screenshot of the knative eventing operator

**Steps to Reproduce**
1. view file [knative-serving-operator-screen.png](https://github.com/openshift-knative/docs/blob/f055c805488c9a02bacc56e6a3e5520ede4bf495/modules/ROOT/assets/images/knative-serving-operator-screen.png) - or view [step 3 of the docs](https://openshift-knative.github.io/docs/docs/proc_knative-serving-v071.html#_installing_the_knative_serving_operator)

**Expected Behavior**
It should be a screenshot of the knative serving operator

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by joaedwar** [comment]
Thanks Martin!!
